### ISSUE TITLE
EINVAL: invalid argument, read

### ISSUE THREAD

**Issue by DaleMckeown** [npm/gently-rm#2]
Hi,

Sorry, no idea if this is you or not...

Updated to node 8.11.1, repulling all packagaes from NPM, and this happens:

```
7211 silly saveTree `-- vue@2.5.16
7212 verbose stack Error: EINVAL: invalid argument, read
7212 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\rm.js:245:7
7212 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
7212 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:287:18
7212 verbose stack     at FSReqWrap.oncomplete (fs.js:153:5)
7213 verbose cwd h:\Git\UoL-Templates\Cwd6-Theme\node_modules
7214 verbose Windows_NT 10.0.16299
7215 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
7216 verbose node v8.11.1
7217 verbose npm  v5.6.0
7218 error code EINVAL
7219 error EINVAL: invalid argument, read
7220 verbose exit [ 1, true ]
```
Any ideas?

Thanks

**Comment by Nomaq** [comment]
Hi @DaleMckeown i have the same problem did you manage to fix it?

**Comment by DaleMckeown** [comment]
Nope. This forced me to abandon node 8!

**Comment by Nomaq** [comment]
@DaleMckeown which node version are you using now? is it working by changing the node version?

**Comment by DaleMckeown** [comment]
Whatever is bundled with VS2017 - I think node 6.

**Comment by msatkevich** [comment]
Hi,
I was able to resolve this problem by moving my project off my SD card, which is formatted as "exFAT" to my C: drive, which is NTFS.
Hopefully that works for you.
Mike

**Comment by fifn2** [comment]
@msatkevich That woked for me! 😄

**Comment by pandasauce** [comment]
The issue may need to be renamed to "no support for exFAT". In my case it's an external SSD that causes the problem and it's not like I will be reformatting that workhorse over this issue with JS.

**Comment by hykilpikonna** [comment]
I'm having this issue too, but I'm stuck on exFAT or FAT32 because I have to work between Windows and macOS... And after some testing, it is found that it happens on both exFAT and FAT32.

The problem occurs after `npm install` on a fresh clone of my project and then `npm audit fix`.

Are there any workarounds?

**Comment by dunkfordyce** [comment]
I also have this problem on exFAT

**Comment by ghost** [comment]
Hi, old me!

This error has randomly come back for me in npm 6.14.8.

I have to go to NTFS this time to resolve.
